import type { Match, Venue, FanProfile, LiveMatchState } from './types';

export const MOCK_MATCHES: Match[] = [
  {
    id: 'match-live-001',
    homeTeam: { id: 'bra', name: 'Brazil', flag: '🇧🇷', primaryColor: '#009c3b' },
    awayTeam: { id: 'usa', name: 'USA', flag: '🇺🇸', primaryColor: '#b22234' },
    kickoffUTC: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    venue: 'SoFi Stadium',
    city: 'Los Angeles',
    stage: 'qf',
    status: 'live',
    score: { home: 2, away: 1 },
  },
  {
    id: 'match-upcoming-002',
    homeTeam: { id: 'arg', name: 'Argentina', flag: '🇦🇷', primaryColor: '#74acdf' },
    awayTeam: { id: 'fra', name: 'France', flag: '🇫🇷', primaryColor: '#0055a4' },
    kickoffUTC: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    venue: 'Rose Bowl',
    city: 'Pasadena',
    stage: 'sf',
    status: 'upcoming',
  },
  {
    id: 'match-finished-003',
    homeTeam: { id: 'ger', name: 'Germany', flag: '🇩🇪', primaryColor: '#000000' },
    awayTeam: { id: 'esp', name: 'Spain', flag: '🇪🇸', primaryColor: '#aa151b' },
    kickoffUTC: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    venue: 'MetLife Stadium',
    city: 'East Rutherford',
    stage: 'group',
    status: 'finished',
    score: { home: 1, away: 3 },
  },
];

export const MOCK_VENUES: Venue[] = [
  {
    id: 'venue-001',
    name: "Murphy's Irish Pub",
    address: '3412 Mission St, San Francisco, CA 94110',
    lat: 37.7525,
    lng: -122.4183,
    phone: '+14155550101',
    type: 'bar',
    capacity: 'medium',
    atmosphere: 'electric',
    amenities: ['Big Screen', 'Full Bar', 'Happy Hour', 'Standing Room'],
    rating: 4.6,
    priceRange: 2,
    rsvpAvailable: true,
  },
  {
    id: 'venue-002',
    name: 'Fútbol Cantina',
    address: '789 Valencia St, San Francisco, CA 94110',
    lat: 37.7609,
    lng: -122.4220,
    phone: '+14155550102',
    type: 'restaurant',
    capacity: 'large',
    atmosphere: 'lively',
    amenities: ['Big Screen', 'Full Bar', 'Kitchen', 'Reservations', 'Outdoor Patio'],
    rating: 4.4,
    priceRange: 2,
    rsvpAvailable: true,
  },
  {
    id: 'venue-003',
    name: 'The Stadium Club',
    address: '1234 Market St, San Francisco, CA 94102',
    lat: 37.7749,
    lng: -122.4194,
    phone: '+14155550103',
    type: 'bar',
    capacity: 'large',
    atmosphere: 'electric',
    amenities: ['Multiple Big Screens', 'Full Bar', 'Dedicated Sports Sound', 'VIP Areas'],
    rating: 4.7,
    priceRange: 3,
    rsvpAvailable: true,
  },
  {
    id: 'venue-004',
    name: 'Dolores Park Fan Zone',
    address: 'Dolores Park, 19th St & Dolores St, San Francisco, CA 94114',
    lat: 37.7596,
    lng: -122.4269,
    phone: '+14155550104',
    type: 'fan_zone',
    capacity: 'large',
    atmosphere: 'electric',
    amenities: ['Giant Screen', 'Food Trucks', 'Beer Garden', 'Family Area'],
    rating: 4.8,
    priceRange: 1,
    rsvpAvailable: false,
  },
  {
    id: 'venue-005',
    name: 'The Locals',
    address: '2901 24th St, San Francisco, CA 94110',
    lat: 37.7523,
    lng: -122.4098,
    phone: '+14155550105',
    type: 'bar',
    capacity: 'intimate',
    atmosphere: 'casual',
    amenities: ['Big Screen', 'Craft Beer', 'Neighborhood Vibe'],
    rating: 4.3,
    priceRange: 1,
    rsvpAvailable: true,
  },
  {
    id: 'venue-006',
    name: 'Pitch Perfect Sports Bar',
    address: '456 Haight St, San Francisco, CA 94117',
    lat: 37.7702,
    lng: -122.4439,
    phone: '+14155550106',
    type: 'bar',
    capacity: 'medium',
    atmosphere: 'lively',
    amenities: ['Big Screen', 'Full Bar', 'Pool Tables', 'Happy Hour Specials'],
    rating: 4.2,
    priceRange: 2,
    rsvpAvailable: true,
  },
  {
    id: 'venue-007',
    name: 'Brazilian BBQ & Sports',
    address: '890 Folsom St, San Francisco, CA 94107',
    lat: 37.7785,
    lng: -122.4022,
    phone: '+14155550107',
    type: 'restaurant',
    capacity: 'medium',
    atmosphere: 'lively',
    amenities: ['Big Screen', 'Full Bar', 'Brazilian Menu', 'Happy Hour'],
    rating: 4.5,
    priceRange: 2,
    rsvpAvailable: true,
  },
  {
    id: 'venue-008',
    name: 'The Overlook Rooftop',
    address: '101 Howard St, San Francisco, CA 94105',
    lat: 37.7885,
    lng: -122.3951,
    phone: '+14155550108',
    type: 'bar',
    capacity: 'medium',
    atmosphere: 'casual',
    amenities: ['Outdoor Screen', 'Cocktail Bar', 'City Views', 'Reservations'],
    rating: 4.4,
    priceRange: 3,
    rsvpAvailable: true,
  },
];

export const DEMO_PROFILE: FanProfile = {
  userId: 'demo-user-001',
  favoriteTeams: ['bra', 'usa'],
  watchStyle: 'social',
  budgetRange: 2,
  maxTravelMinutes: 30,
  notificationsEnabled: true,
  departureAlertMinutes: 60,
  name: 'Alex',
  partySize: 3,
};

export const MOCK_LIVE_STATE: LiveMatchState = {
  matchId: 'match-live-001',
  minute: 67,
  score: { home: 2, away: 1 },
  possession: { home: 58, away: 42 },
  keyEvents: [
    {
      id: 'evt-001',
      minute: 1,
      type: 'kickoff',
      team: 'bra',
      description: "The referee blows his whistle — Brazil vs USA is underway at SoFi Stadium!",
    },
    {
      id: 'evt-002',
      minute: 23,
      type: 'goal',
      team: 'bra',
      player: 'Vinicius Jr.',
      description: "GOAL! Vinicius Jr. fires home a stunning left-footed strike to open the scoring for Brazil!",
    },
    {
      id: 'evt-003',
      minute: 38,
      type: 'yellow_card',
      team: 'usa',
      player: 'Christian Pulisic',
      description: "Pulisic picks up a yellow card for a late challenge in midfield — he'll need to be careful.",
    },
    {
      id: 'evt-004',
      minute: 45,
      type: 'halftime',
      team: 'bra',
      description: "Half-time! Brazil lead 1-0 thanks to Vinicius Jr's brilliant opener. USA need to respond.",
    },
    {
      id: 'evt-005',
      minute: 54,
      type: 'goal',
      team: 'usa',
      player: 'Folarin Balogun',
      description: "USA are level! Balogun pounces on a defensive error to tap home and silence the Brazilian fans.",
    },
    {
      id: 'evt-006',
      minute: 67,
      type: 'goal',
      team: 'bra',
      player: 'Rodrygo',
      description: "Brazil retake the lead! Rodrygo latches onto a through ball and finishes coolly to make it 2-1!",
    },
  ],
};
